import "@/styles/globals.css";

import { type Metadata } from "next";
import { Press_Start_2P } from "next/font/google";

import background from "@/assets/img/flappy-frog-bg.png";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Flappy Frog",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const press_start_2P = Press_Start_2P({
  weight: ["400"],
  subsets: ["latin"],
  style: "normal",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${press_start_2P.className}`}>
      <body cz-shortcut-listen="true">
        <Providers>
          <div
            className={`flex min-h-screen w-full flex-col items-center justify-center overflow-hidden bg-cover bg-center bg-repeat`}
            style={{ backgroundImage: `url(${background.src})` }}
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
